### ISSUE TITLE
price history graph per asset on dashboard

### ISSUE THREAD

**Issue by severinwullschleger** [THORWallet/thorwallet-react-native#26]
i'm fetching the history and you can display it.

![image](https://user-images.githubusercontent.com/9573561/124789442-94165e80-df4a-11eb-9dc3-9ff4959993fa.png)

**Comment by severinwullschleger** [comment]
added use pool history hook. pulls the pool history in 1 hour intervals for 7 days.

not sure if the hook is correct. feel free to change it. 

https://github.com/THORWallet/thorwallet-react-native/commit/910c6e510864173767d88837d2478072bea3e169

sorry for not doing a PR

**Comment by severinwullschleger** [comment]
if  too many data points you can adjust the interval to days or so

**Comment by JonnyBurger** [comment]
Thanks 🚀
