### ISSUE TITLE
Can't find variable Webassembly with Thorchain Client

### ISSUE THREAD

**Issue by lucaspelloni2** [THORWallet/thorwallet-react-native#4]
Getting this error when trying to import ThorchainClient in `use-chain-clients.ts`. 

![simulator_screenshot_46A40F53-D317-4D14-9FA1-81552B69BA04](https://user-images.githubusercontent.com/17781533/121486401-65e84200-c9d1-11eb-8741-2ae6a6c267c8.png)

Working on simulator, no other errors so far for the other chains (apart of performance issues)

**Comment by JonnyBurger** [comment]
Fixed in 5370b04b1a52512dc9b1a31819e74e1f52ce5e9e
